# Generated by Django 4.2.16 on 2024-11-18 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracker", "0002_alter_foodentry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodentry",
            name="date",
        ),
    ]
