# Generated by Django 4.2.16 on 2024-11-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracker", "0006_alter_calculatetdee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodentry",
            name="calories_unit",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="carbs_unit",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="fat_unit",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AddField(
            model_name="foodentry",
            name="protein_unit",
            field=models.CharField(default="", max_length=10),
        ),
    ]
