# Generated by Django 4.2.16 on 2024-11-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracker", "0007_foodentry_calories_unit_foodentry_carbs_unit_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodentry",
            name="calories_unit",
        ),
        migrations.RemoveField(
            model_name="foodentry",
            name="carbs_unit",
        ),
        migrations.RemoveField(
            model_name="foodentry",
            name="fat_unit",
        ),
        migrations.RemoveField(
            model_name="foodentry",
            name="protein_unit",
        ),
        migrations.AddField(
            model_name="foodentry",
            name="meal_type",
            field=models.CharField(
                choices=[
                    ("breakfast", "Breakfast"),
                    ("lunch", "Lunch"),
                    ("dinner", "Dinner"),
                    ("snacks", "Snacks"),
                ],
                default="breakfast",
                max_length=10,
            ),
        ),
    ]
