# Generated by Django 4.2.16 on 2024-11-18 01:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("food_tracker", "0003_remove_foodentry_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodentry",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
