# Generated by Django 4.2.16 on 2024-11-19 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("food_tracker", "0005_calculatetdee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculatetdee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
