# Generated by Django 4.2.16 on 2024-10-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weightlog",
            options={"ordering": ("weight",)},
        ),
        migrations.AlterField(
            model_name="weightlog",
            name="weight",
            field=models.FloatField(),
        ),
    ]
