# Generated by Django 4.2.16 on 2024-10-23 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tracker", "0004_alter_weightlog_options_alter_weightlog_weight"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("gain", "Gain Weight"),
                            ("maintain", "Maintain Weight"),
                            ("lose", "Lose Weight"),
                        ],
                        max_length=10,
                    ),
                ),
                ("target_weight", models.FloatField()),
                ("start_weight", models.FloatField()),
                ("target_date", models.DateField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
