# Generated by Django 4.2.16 on 2024-11-03 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0010_goal_weekly_goal_bodymeasurements"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BodyMeasurements",
        ),
    ]
