# Generated by Django 4.2.16 on 2024-11-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0013_bmilog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bmilog",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
