# Generated by Django 4.2.16 on 2024-11-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0015_alter_goal_target_date_alter_goal_weekly_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="weekly_goal",
            field=models.CharField(
                choices=[
                    ("lose_1", "Lose 1 pound per week"),
                    ("lose_2", "Lose 2 pounds per week"),
                    ("gain_1", "Gain 1 pound per week"),
                    ("gain_2", "Gain 2 pounds per week"),
                ],
                max_length=50,
            ),
        ),
    ]
