# Generated by Django 4.2.16 on 2024-10-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_goal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weightlog",
            options={},
        ),
    ]
