# Generated by Django 4.2.16 on 2024-10-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0006_alter_weightlog_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Goal",
        ),
    ]
