# Generated by Django 4.2.16 on 2024-11-01 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_goal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="goal",
            old_name="current_weight",
            new_name="start_weight",
        ),
    ]
