# Generated by Django 4.2.16 on 2024-11-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_delete_bodymeasurements"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weightlog",
            name="date",
            field=models.DateField(),
        ),
    ]
